name: Deploy React App

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ This allows GitHub Actions to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install `gh-pages`
        run: npm install -g gh-pages

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "123191250+PrincepaulIzuogu@users.noreply.github.com"
          git config --global user.name "PrincepaulIzuogu"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/PrincepaulIzuogu/valentines-app.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
