name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies with Fix
        run: npm install --legacy-peer-deps

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "123191250+PrincepaulIzuogu@users.noreply.github.com"
          git config --global user.name "PrincepaulIzuogu"
          git remote set-url origin https://$GH_TOKEN@github.com/PrincepaulIzuogu/valentines-app.git
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
